name: dynamics
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.17=h4ee41c1_0
  - pip=25.2=pyhc872135_0
  - python=3.13.7=hc28b8d9_100_cp313
  - python_abi=3.13=1_cp313
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py313hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - et-xmlfile==2.0.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.60.0
      - h5py==3.14.0
      - hedtools==0.7.0
      - imageio==2.37.2
      - inflect==7.5.0
      - ipykernel==7.0.1
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - more-itertools==10.8.0
      - nbformat==5.10.4
      - nbstripout==0.8.1
      - nest-asyncio==1.6.0
      - numpy==2.3.3
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.36.2
      - rpds-py==0.27.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - wcwidth==0.2.13
      - wordcloud==1.9.4
      - xlrd==2.0.2
prefix: /Users/aim/miniconda3/envs/dynamics
